name: React App Deploy to Surge
on:
  push:
    branches: [ main ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Github action for yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build React App
      run: sudo yarn build
      
    - name: Install Surge
      run: sudo npm install -g surge

    - name: Deploy to Surge
      run: surge ./build ashraf-food.surge.sh --token ${{ secrets.PROJECT_TOKEN }}